"use strict";

app.controller("NewSkillCtrl", function($scope, AuthFactory, HeroFactory, $location) {

	$scope.addNewSkill = function() {
		$scope.newSkill.uid = AuthFactory.getUser();
		HeroFactory.postNewSkill($scope.newSkill)
		.then(function() {
			$location.url("/tracker/hero");
		});
	};

	$scope.newSkill = {
		acrobatics : false,
		acrobaticsRanks : "",
		acrobaticsMM : "",
		appraise : false,
		appraiseRanks : "",
		appraiseMM : "",
		bluff : false,
		bluffRanks : "",
		bluffMM : "",
		climb : false,
		climbRanks : "",
		climbMM : "",
		craft1 : false,
		craft1Type : "",
		craft1TypeRanks : "",
		craft1TypeMM : "",
		craft2 : false,
		craft2Type : "",
		craft2TypeRanks : "",
		craft2TypeMM : "",
		craft3 : false,
		craft3Type : "",
		craft3TypeRanks : "",
		craft3TypeMM : "",
		diplomacy : false,
		diplomacyRanks : "",
		diplomacyMM : "",
		disableDevice : false,
		disableDeviceRanks : "",
		disableDeviceMM : "",
		disguise : false,
		disguiseRanks : "",
		disguiseMM : "",
		escapeArtist : false,
		escapeArtistRanks : "",
		escapeArtistMM : "",
		fly : false,
		flyRanks : "",
		flyMM : "",
		handleAnimal : false,
		handleAnimalRanks : "",
		handleAnimalMM : "",
		heal : false,
		healRanks : "",
		healMM : "",
		intimidate : false,
		intimidateRanks : "",
		intimidateMM : "",
		knowArcana : false,
		knowArcanaRanks : "",
		knowArcanaMM : "",
		knowDungeon : false,
		knowDungeonRanks : "",
		knowDungeonMM : "",
		knowGeography : false,
		knowGeographyRanks : "",
		knowGeographyMM : "",
		knowHistory : false,
		knowHistoryRanks : "",
		knowHistoryMM : "",
		knowLocal : false,
		knowLocalRanks : "",
		knowLocalMM : "",
		knowNature : false,
		knowNatureRanks : "",
		knowNatureMM : "",
		knowNobility : false,
		knowNobilityRanks : "",
		knowNobilityMM : "",
		knowPlanes : false,
		knowPlanesRanks : "",
		knowPlanesMM : "",
		knowReligion : false,
		knowReligionRanks : "",
		knowReligionMM : "",
		linguistics : false,
		linguisticsRanks : "",
		linguisticsMM : "",
		perception : false,
		perceptionRanks : "",
		perceptionMM : "",
		perform1 : false,
		perform1Type : "",
		perform1TypeRanks : "",
		perform1TypeMM : "",
		perform2 : false,
		perform2Type : "",
		perform2TypeRanks : "",
		perform2TypeMM : "",
		profession1 : false,
		profession1Type : "",
		profession1TypeRanks : "",
		profession1TypeMM : "",
		profession2 : false,
		profession2Type : "",
		profession2TypeRanks : "",
		profession2TypeMM : "",
		ride : false,
		rideRanks : "",
		rideMM : "",
		senseMotive : false,
		senseMotiveRanks : "",
		senseMotiveMM : "",
		sleightOfHand : false,
		sleightOfHandRanks : "",
		sleightOfHandMM : "",
		spellCraft : false,
		spellCraftRanks : "",
		spellCraftMM : "",
		stealth : false,
		stealthRanks : "",
		stealthMM : "",
		survival : false,
		survivalRanks : "",
		survivalMM : "",
		swim : false,
		swimRanks : "",
		swimMM : "",
		useMagicDevice : false,
		useMagicDeviceRanks : "",
		useMagicDeviceMM : ""
	};
});
		


